version: 3
jobs:
  build:
    docker:
      - image: circleci/python:3.11-bookworm

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements-devel.txt" }}

      - run:
          name: Install dependencies
          command: |
            mkdir -p ./venv
            virtualenv ./venv
            source venv/bin/activate
            pip install tox
            pip install -r requirements-devel.txt

      - save_cache:
          paths:
            - ./venv
            - ./.tox
          key: v1-dependencies-{{ checksum "requirements-devel.txt" }}

      - run:
          name: Run tests
          command: |
            source venv/bin/activate
            tox

      - store_artifacts:
          path: test-report.xml
          destination: test-report.xml
